# Generated by Django 6.0.1 on 2026-02-03 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('region', models.CharField(choices=[('adamaoua', 'Adamaoua'), ('centre', 'Centre'), ('est', 'Est'), ('extreme_nord', 'Extrême-Nord'), ('littoral', 'Littoral'), ('nord', 'Nord'), ('nord_ouest', 'Nord-Ouest'), ('ouest', 'Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=20, verbose_name='région')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('quarter', models.CharField(blank=True, max_length=100, null=True, verbose_name='quartier')),
                ('address', models.TextField(verbose_name='adresse complète')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'localisation',
                'verbose_name_plural': 'localisations',
                'ordering': ['city', 'quarter'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catégorie de propriété',
                'verbose_name_plural': 'catégories de propriétés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('for_sale', 'À vendre'), ('for_rent', 'À louer'), ('sold', 'Vendu'), ('rented', 'Loué'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='statut')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='superficie (m²)')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='chambres')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='salles de bain')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='places de parking')),
                ('has_kitchen', models.BooleanField(default=True, verbose_name='cuisine')),
                ('has_living_room', models.BooleanField(default=True, verbose_name='salon')),
                ('has_dining_room', models.BooleanField(default=False, verbose_name='salle à manger')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='balcon')),
                ('has_garden', models.BooleanField(default=False, verbose_name='jardin')),
                ('has_pool', models.BooleanField(default=False, verbose_name='piscine')),
                ('has_garage', models.BooleanField(default=False, verbose_name='garage')),
                ('has_security', models.BooleanField(default=False, verbose_name='sécurité')),
                ('has_internet', models.BooleanField(default=False, verbose_name='internet')),
                ('has_ac', models.BooleanField(default=False, verbose_name='climatisation')),
                ('is_featured', models.BooleanField(default=False, verbose_name='en vedette')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='nombre de favoris')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL, verbose_name='agent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'propriété',
                'verbose_name_plural': 'propriétés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='légende')),
                ('is_primary', models.BooleanField(default=False, verbose_name='image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'image de propriété',
                'verbose_name_plural': 'images de propriétés',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='properties.propertycategory')),
            ],
            options={
                'verbose_name': 'type de propriété',
                'verbose_name_plural': 'types de propriétés',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='requête de recherche')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filtres')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='nombre de résultats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historique de recherche',
                'verbose_name_plural': 'historiques de recherche',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_3e16cc_idx'),
        ),
    ]
