# Generated by Django 6.0.1 on 2026-02-03 08:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'Général'), ('bug', "Bug/Rapport d'erreur"), ('suggestion', 'Suggestion'), ('complaint', 'Plainte'), ('praise', 'Éloge')], default='general', max_length=20, verbose_name='type de feedback')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email de contact')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='résolu')),
                ('response', models.TextField(blank=True, null=True, verbose_name='réponse')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='date de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "feedback d'application",
                'verbose_name_plural': "feedbacks d'application",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('title', models.CharField(max_length=200, verbose_name="titre de l'avis")),
                ('comment', models.TextField(verbose_name='commentaire')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='achat vérifié')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='nombre de likes')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approuvé')),
                ('is_edited', models.BooleanField(default=False, verbose_name='modifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='propriété')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='légende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
            options={
                'verbose_name': "image d'avis",
                'verbose_name_plural': "images d'avis",
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "like d'avis",
                'verbose_name_plural': "likes d'avis",
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['property', 'rating'], name='reviews_rev_propert_1e2947_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('user', 'review')},
        ),
    ]
